<?php echo $this->doctype() . PHP_EOL?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php 
echo $this->headTitle() . PHP_EOL;
echo $this->headMeta() . PHP_EOL;
echo $this->headLink() . PHP_EOL;
echo $this->headScript() . PHP_EOL; 
?>
<link rel="icon" type="image/x-icon" href="/favicon.ico" />
<!--[if IE]><link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" /><![endif]-->
</head>
<body>

<div id="wrapper">

  <!-- start of header -->
  <div id="header">

  </div>
  <!-- end of header -->
  
  <!-- start of page wrapper -->
  <div id="page">
    <!-- start of content -->
    <div id="content">
    <?php echo $this->layout()->content . PHP_EOL?>
    </div>
    <!-- end of content -->
  </div>
  <!-- end of page wrapper -->
</div>

<?php
echo $this->inlineScript() . PHP_EOL;
?>

</body>
</html>
